name: image_upload_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  cupertino_icons: ^1.0.6
  image_picker: ^0.8.4+1
  http: ^0.13.3
  permission_handler: ^10.2.0
  translator: ^0.1.7
  shared_preferences: ^2.0.15
  webview_flutter: ^3.0.0
  webview_windows: ^0.0.1+3
  url_launcher: ^6.0.0
  lottie: ^2.2.0
  connectivity_plus: ^2.3.4 # Corrected indentation
  geolocator: ^7.0.3
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true